version: '3.8'

services:
  beer-quest:
    build:
      args:
        NODE_ENV: development
    image: beer-quest-development
    container_name: beer-quest-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./src/:/home/node/app/src/
      - ./package.json:/home/node/app/package.json
