version: '3.8'

services:
  beer-quest:
    build:
      args:
        NODE_ENV: production
      context: .
    container_name: beer-quest
    environment: {}
    image: beer-quest
    volumes:
      - ./src/:/home/node/app/src/
      - ./package.json:/home/node/app/package.json
