version: '3.8'

services:
  beer-quest:
    build:
      args:
        NODE_ENV: development
    container_name: beer-quest-development
    image: beer-quest-development
    ports:
      - "3000:3000"
      - "9229:9229"
